[project]
name = "Inversion-DNSBL-Generator"
version = "0.0.1"
description = "Generate malicious URL blocklists for DNSBL applications like pfBlockerNG or Pi-hole by scanning various public URL sources using the Safe Browsing API from Google and/or Yandex."
authors = [{ name = "Wu Tingfeng", email = "wutingfeng@outlook.com" }]
requires-python = ">=3.12"
readme = "README.md"
license = "BSD-3-Clause"
dependencies = [
    "aiofiles==24.1.0",
    "aiohttp==3.11.18",
    "apsw==3.49.2.0",
    "bandit==1.8.3",
    "beautifulsoup4==4.13.4",
    "black==25.1.0",
    "feedparser==6.0.11",
    "flake8==7.2.0",
    "lxml==5.4.0",
    "more-itertools==10.7.0",
    "mypy==1.15.0",
    "mypy-extensions==1.1.0",
    "pygithub==2.6.1",
    "pytest==8.3.5",
    "pytest-cov==6.1.1",
    "pytest-mock==3.14.0",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.1.0",
    "ray==2.46.0",
    "spavro",
    "tldextract==5.3.0",
    "tqdm==4.67.1",
    "types-aiofiles==24.1.0.20250516",
    "types-beautifulsoup4==4.12.0.20250516",
    "types-python-dateutil==2.9.0.20250516",
    "urlextract==1.9.0",
]

[dependency-groups]
dev = [
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["Inversion-DNSBL-Generator"]

[tool.uv.sources]
spavro = { git = "https://github.com/mikepk/spavro.git", rev = "e9fee6e395b555b62cd014652c0f8b111f5e3a24" }
