from modules.feeds.afnic import AFNIC
from modules.feeds.aws_ec2 import AmazonWebServicesEC2
from modules.feeds.cubdomain import CubDomain
from modules.feeds.domainsproject import DomainsProject
from modules.feeds.googletag import GoogleTag
from modules.feeds.icann import ICANN
from modules.feeds.internet_ee import InternetEE
from modules.feeds.ipv4 import Ipv4
from modules.feeds.openintel import OpenINTEL
from modules.feeds.registrar_r01 import RegistrarR01
from modules.feeds.sk_nic import SKNIC
from modules.feeds.switch_ch import SwitchCH
from modules.feeds.top1m import Top1M
from modules.feeds.top10m import Top10M
